//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker
{
    using System;
    
    public enum Roles : int
    {
        Engineer = 0,
        Mechanic = 1,
        Electrican = 2,
        Manager = 3,
        CEO = 4
    }
}
